### ISSUE TITLE
TypeError: float() argument must be a string or a number, not 'map'

### ISSUE THREAD

**Issue by ZhenhuiTang** [williamleif/graphsage-simple#13]
Traceback (most recent call last):
  File "/home/machinelearning/anaconda3/envs/graphsage-simple-master/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/machinelearning/anaconda3/envs/graphsage-simple-master/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/machinelearning/Documents/graphsage-simple-master/graphsage/model.py", line 183, in <module>
    run_cora()
  File "/home/machinelearning/Documents/graphsage-simple-master/graphsage/model.py", line 69, in run_cora
    feat_data, labels, adj_lists = load_cora()
  File "/home/machinelearning/Documents/graphsage-simple-master/graphsage/model.py", line 49, in load_cora
    feat_data[i, :] = map(float(), info[1:-1])
TypeError: float() argument must be a string or a number, not 'map'

**Comment by Andy1314Chen** [comment]
In python3:
```python
feat_data[i, :] = list(map(float(), info[1:-1]))
```

**Comment by yeyingdege** [comment]
Can just use`feat_data[i, :] = info[1:-1]`

**Comment by yeyingdege** [comment]
> In python3:
> 
> ```python
> feat_data[i, :] = list(map(float(), info[1:-1]))
> ```

Use `feat_data[i, :] = list(map(float, info[1:-1]))`
